services:
  - type: web
    name: weather-frontend
    env: static
    buildCommand: npm install && npm run build
    staticPublishPath: dist
    envVars:
      - key: VITE_API_BASE_URL
        value: https://weather-backend-aagb.onrender.com
  
