services:
  - type: web
    name: weather-frontend
    env: node
    buildCommand: "npm install && npm run build"
    startCommand: "serve -s build"
    envVars:
      - key: VITE_API_BASE_URL
        value: "https://weather-backend.onrender.com"  # Update with the correct backend URL after deployment
