services:
  - type: web
    name: weather-backend
    env: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn weather_backend.wsgi:application
    envVars:
      - key: DJANGO_SETTINGS_MODULE
        value: weather_backend.settings
      - key: PYTHON_VERSION
        value: 3.11
      - key: SECRET_KEY
        generateValue: true
      - key: ALLOWED_HOSTS
        value: .onrender.com
    buildFilter:
      paths:
        - backend/**/*
    repo: https://github.com/SamMochache/WEATHER-APP
    rootDir: backend

  - type: web
    name: weather-frontend
    env: static
    plan: free
    buildCommand: npm install && npm run build
    staticPublishPath: dist
    buildFilter:
      paths:
        - frontend/**/*
    repo: https://github.com/SamMochache/WEATHER-APP
    rootDir: frontend
