services:
  - type: web
    name: weather-backend
    env: python
    buildCommand: "pip install -r requirements.txt"
    startCommand: "gunicorn weather_backend.wsgi"
    envVars:
      - key: DJANGO_SECRET_KEY
        value: "(7xdjango-insecure-awwr*%jjyna%e$gy=s0n2!x+d-(yx8p$vt2w&eyn0e!p@fy"
      - key: DEBUG
        value: "false"
      - key: OPENWEATHER_API_KEY
        value: "5cd5a164d76991bff4efa418ef46f499"
      - key: DATABASE_URL
        value: "sqlite:///db.sqlite3"
